config/routes.rb
Rails.application.routes.draw do
  
  root 'gossips#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :gossips do
    resources :comments
  end

  resources :cities, only: [:index, :show]
    
  get 'welcomes/:first_name', to: 'welcomes#index'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, presence: true
    
    belongs_to :gossip
    belongs_to :user
    has_many :sub_comments
    has_many :likes, as: :likable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, length: { in: 3..14}, presence: true
    validates :content, presence: true
    
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :gossip_tags
    has_many :tags, through: :gossip_tags, dependent: :destroy
    has_many :likes, as: :likable
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    validates :tag_id, uniqueness: { scope: :gossip_id }

    belongs_to :gossip
    belongs_to :tag 
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :likable, :polymorphic => true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/sub_comment.rb
class SubComment < ApplicationRecord
    belongs_to :comment
    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossip_tags
    has_many :gossips, through: :gossip_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :password, presence: true, length: { minimum: 6 }

    belongs_to :city
    has_many :gossips
    has_many :comments
    has_many :likes
    has_many :sub_comments
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id]) 
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @gossips = Gossip.includes(:user).all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create 
    @gossip = Gossip.new(gossip_params) 
    @gossip.user = current_user
    @gossip.tags << Tag.find(params[:tags_id])
    if @gossip.save
      flash[:notice] = 'New gossip created !'
      redirect_to root_path
    else
      flash[:alert] = @gossip.errors.full_messages
      render 'new'
    end
  end

  def edit 
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.tags << Tag.find(params[:tags_id])
    if @gossip.update(gossip_params)
      flash[:notice] = 'gossip updated !'
      redirect_to @gossip
    else
      flash[:alert] = @gossip.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy

    redirect_to root_path
  end

  private
    def gossip_params
      params.require(:gossip).permit(:title, :content, :tag_ids => [])
    end

    def correct_user
      gossip = Gossip.find(params[:id])
      redirect_to root_path unless current_user == gossip.user
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user, only: [:update, :create, :destroy]

    def create
    end

    def destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params.merge(city: City.all.sample))
    if @user.save
      log_in(@user)
      flash[:notice] = "Welcome !"
      redirect_to root_path
    else
      flash[:alert] = @user.errors.full_messages
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @city = City.find_by(name: params[:city])
    if @city == nil
      @city = City.create(name: params[:city])
    end
    @user = User.find(user_params.merge(city: @city)) 
    if @user.update(user_params.merge(city: @city))
      flash[:notice] = "Your account has been updated !"
      redirect_to root_path
    else
      flash[:alert] = @user.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @user = Gossip.find(params[:id])
    @user.destroy

    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/cities/index.html.erb
<h1>Cities Gossips</h1>

<div class="row">
    <% @cities.each do |city|%>
    <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                <div class="card-body">
                   <p class="card-text"><%= link_to "#{city.name}", city_path(city.id)%></p>
                </div>
            </div>
        </div> 
    <% end %>
</div>

app/views/cities/show.html.erb
<h1>Gossips from the city of <%= @city.name %></h1>

<div class="row">
    <% @city.users.each do |user_city|%>
        <% user_city.gossips.sort_by(&:created_at).reverse.each do |gossip|%>
            <div class="card w-100">
                <div class="card-body">
                    <h5 class="card-text"><%= gossip.title %></h5>
                    <blockquote class="blockquote mb-0">
                    <p><%= gossip.content %></p>
                    <footer class="blockquote-footer">
                        <small>Author : <cite title="Source Title"><%= gossip.user.first_name %></cite></small><br/>
                         <% if !gossip.tags.empty? %>
                           <cite>Tags:</cite>
                            <% gossip.tags.each do |tag| %>
                                <span class="badge badge-info"><%= tag.title %></span>
                            <% end %>
                        <% end %><br/>
                        <small>Number of comments : <%= gossip.comments.count %></small><br/>
                        <small><cite title="Source Title"><%= gossip.created_at.strftime("Created : %m/%d/%Y at %I:%M %p") %></cite></small>
                        <p><%= link_to "Show Gossip", gossip_path(gossip), class: "btn btn-outline-secondary btn-block" %></p>
                    </footer>
                    </blockquote>
                </div>
            </div>
        <% end %>    
    <% end %>
</div>

app/views/gossips/edit.html.erb
<%= form_with model: @gossip do |f| %>
    <form>
        <div class="form-group">
            <%= f.label :title %> 
            <%= f.text_field :title, class: "form-control" %>
            <%= f.label :content %>
            <%= f.text_field :content, class: "form-control"%>
            <% if !@gossip.tags.empty? %>
                <%= f.label :tags %> 
                <% @gossip.tags.each do |tag| %>
                    <span class="badge badge-info"><%= tag.title %></span>
                <% end %><br/>
            <% end %>
            <%= select_tag :tags_id, options_from_collection_for_select(Tag.all, "id", "title"), class: "checkbox", multiple: true, classe: 'selected-select', include_blank: 'Choose tag' %>
            <p><%= f.submit 'Edit Gossip', class: "btn btn-secondary" %></p> 
        </div>
   </form>
<% end %>

app/views/gossips/index.html.erb
<!-- Vue de la page d'accueil de l'appication -->
<h2>HI <%= params[:id] %> ! Welcome to the Gossips Center :</h2>
<!-- Boucle qui parcours tous les gossips -->
<div class="row">
    <% @gossips.sort_by(&:created_at).reverse.each do |gossip|%>
    <!-- Affichage des information de chaques gossips -->
            <div class="card w-100">
                <div class="card-body">
                    <h5 class="card-text"><%= gossip.title %></h5>
                    <blockquote class="blockquote mb-0">
                    <p><%= gossip.content %></p>
                    <footer class="blockquote-footer">
                        <small>Author : <cite title="Source Title"><%= gossip.user.first_name %></cite></small><br/>
                         <% if !gossip.tags.empty? %>
                           <cite>Tags:</cite>
                            <% gossip.tags.each do |tag| %>
                                <span class="badge badge-info"><%= tag.title %></span>
                            <% end %>
                        <% end %><br/>
                        <small>Number of comments : <%= gossip.comments.count %></small><br/>
                        <small><cite title="Source Title"><%= gossip.created_at.strftime("Created : %m/%d/%Y at %I:%M %p") %></cite></small>
                        <p><%= link_to "Show Gossip", gossip_path(gossip), class: "btn btn-outline-secondary btn-block" %></p>
                    </footer>
                    </blockquote>
                </div>
            </div>
    <% end %>
</div>

app/views/gossips/new.html.erb
<h1>New Gossip</h1>

<%= form_with model: @gossip do |f| %>
    <form>
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
            <%= f.label :content %>
            <%= f.text_field :content, class: 'form-control'%><br/>
            <%= f.label :tags %>
            <%= select_tag :tags_id, options_from_collection_for_select(Tag.all, "id", "title"), include_blank: 'Choose tag' %><br/>
            <p><%= f.submit 'New Gossip', class: "btn btn-secondary" %></p> 
        </div>
    </form>
<% end %>

app/views/gossips/show.html.erb
<h2 class="text-center">GOSSIP <%= params[:id] %></h2><br/>
<div class="card w-100">
  <div class="card-body">
    <h3 class="card-title">Title : 
    <%= @gossip.title %></h3>
    <h5 class="card-title">Content:</h5>
    <p class="card-text"><%= @gossip.content %></p>
    <h5 class="card-title">Author:</h5>
    <p class="card-text"><%= link_to "#{@gossip.user.first_name + " " + @gossip.user.last_name.upcase}", user_path(@gossip.user)%></p>
    <h5 class="card-title">City:</h5>
    <p class="card-text"><%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city)%></p> 
    <% if !@gossip.tags.empty? %>
        <h5 class="card-title">Tags:</h5>
        <% @gossip.tags.each do |tag| %>
            <span class="badge badge-info"><%= tag.title %></span>
        <% end %><br/>
    <% end %>
    <small><cite title="Source Title"><%= @gossip.created_at.strftime("Created : %m/%d/%Y at %I:%M %p") %></cite></small><br/>
    <% if current_user == @gossip.user %>
        <%= link_to 'Edit', edit_gossip_path(@gossip), class: "btn btn-secondary btn-sm" %>
        <%= link_to 'Destroy', gossip_path(@gossip), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div><br/>
<h2 class="text-center">Comments</h2><br/>
<%= form_with url: gossip_comments_path(gossip_id: params[:id]), method: :post do |f| %>
    <div class="card border-light text-center">
        <div class="card-body">
            <%= f.text_field :content, placeholder: "Add a comment", class: "form-control"%><br/>
            <p><%= f.submit 'Post', class: "btn btn-secondary" %></p> 
        </div>
    </div>
<% end %>
<% @gossip.comments.sort_by(&:created_at).reverse.each do |comment|%>
        <div class="card w-100">
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                <p><%= comment.content %></p>
                <footer class="blockquote-footer">
                    <small>Author : <cite title="Source Title"><%= comment.user.first_name %></cite></small><br/>
                </footer>
                </blockquote><br/>
                <% if current_user == @gossip.user %>
                    <%= link_to 'Edit comment', edit_gossip_comment_path(@gossip, comment) %>
                <% end %>
            </div>
        </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Create account :</h1>

<%= form_with model: @user do |f| %>
    <form>
        <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: 'form-control' %>
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>
            <%= f.label :Age %>
            <%= f.text_field :age, class: 'form-control' %>
            <%= f.label :description %>
            <%= f.text_field :description, class: 'form-control' %>
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
            <%= f.label :password %> 
            <%= f.text_field :password, class: 'form-control' %>
            <%= f.label :password_confirmation %>
            <%= f.text_field :password_confirmation, class: 'form-control' %>
            <p><%= f.submit 'Create account', class: "btn btn-secondary" %></p> 
        </div>
   </form>
<% end %>

app/views/users/show.html.erb
<h1>User Page</h1>

    <div class="card w-50">
      <div class="card-body">
        <h5 class="card-title">First name:</h5>
        <p class="card-text"><%= @user.first_name %></p>
        <h5 class="card-title">Last name:</h5>
        <p class="card-text"><%= @user.last_name %></p>
        <h5 class="card-title">Description:</h5>
        <p class="card-text"><%= @user.description %></p>
        <h5 class="card-title">E-mail:</h5>
        <p class="card-text"><%= @user.email %></p>
        <h5 class="card-title">Age:</h5>
        <p class="card-text"><%= @user.age %></p>  
        <h5 class="card-title">City:</h5>
        <p class="card-text"><%= link_to "#{@user.city.name}", city_path(@user.city)%></p>
      </div>
    </div>