config/routes.rb
Rails.application.routes.draw do
  
  root 'gossips#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :gossips do
    resources :comments
  end

  resources :cities, only: [:index, :show]
    
  get 'welcomes/:first_name', to: 'welcomes#index'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, presence: true
    
    belongs_to :gossip
    belongs_to :user
    has_many :sub_comments
    has_many :likes, as: :likable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, length: { in: 3..14}, presence: true
    validates :content, presence: true
    
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :gossip_tags
    has_many :tags, through: :gossip_tags, dependent: :destroy
    has_many :likes, as: :likable
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    validates :tag_id, uniqueness: { scope: :gossip_id }

    belongs_to :gossip
    belongs_to :tag 
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :likable, :polymorphic => true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/sub_comment.rb
class SubComment < ApplicationRecord
    belongs_to :comment
    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossip_tags
    has_many :gossips, through: :gossip_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :password, presence: true, length: { minimum: 6 }

    belongs_to :city
    has_many :gossips
    has_many :comments
    has_many :likes
    has_many :sub_comments
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user, only: [:update, :create, :destroy]

    def create
    end

    def destroy
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_flash_messages.html.erb
<% if notice %>
	<div class='alert alert-success p-2'>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
    <div class='alert alert-danger p-2'>
        <%= alert %>
    </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "The Gossip Projet", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <%= link_to "Cities", cities_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
                <%= link_to "Team", team_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
                <%= link_to "Contact", contact_path, class: "nav-link" %>
            </li>
        </ul>
    </div> 
    <% if current_user %>  
        <%= link_to "New Gossip", new_gossip_path, class: "btn btn-secondary" %>  
        <%= link_to "Log Out", session_path(session.id), method: :delete, class: "btn btn-outline-secondary space_left_button" %>
    <% else %>
        <%= link_to "Sign Up", new_user_path, class: "btn btn-outline-secondary space_left_button" %>
        <%= link_to "Sign In", new_session_path, class: "btn btn-outline-secondary space_left_button" %>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProjet2020</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>  
  </body>
</html>